platform:ios,'10.0'
inhibit_all_warnings!
use_frameworks!
def pods
	pod 'Texture'
	pod 'SnapKit', '~> 4.0.0'
    pod 'Kingfisher', '~> 4.2.0'
	pod 'IGListKit', '~> 3.0'
	pod 'Result', '~> 3.0.0'
	pod 'PromiseKit/Foundation', '~> 4.0'
	pod 'PromiseKit/OMGHTTPURLRQ', '~> 4.0'
end

target 'SwiftDribbble' do
    pods
end

